routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'web']], function () {
    Route::post('/alternative/data', 'AlternativeController@data')->name('alternative.data');
    Route::resource('/alternative', 'AlternativeController');

    Route::post('/criteria/data', 'CriteriaController@data')->name('criteria.data');
    Route::resource('/criteria', 'CriteriaController');

    Route::post('/selection/data', 'SelectionController@data')->name('selection.data');
    Route::resource('/selection', 'SelectionController');

    Route::put('/count-result', 'SelectionController@count')->name('count');
    Route::post('/save-result', 'SelectionController@save_results')->name('result_save');
});

resources/views/alternatives.blade.php
@extends('layouts.app')

@section('title')
    Manajemen Alternatif
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card border-0 shadow w-100">
                <div class="card-body">
                    <table class="table table-hover">
                        <thead class="">
                            <tr>
                                <th>Nama</th>
                                <th>No. Telepon</th>
                                <th>Email</th>
                                <th width="45%">Alamat</th>
                                <th width="15%"></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        let datatable = null;
        let _token = $('meta[name=csrf-token]').attr('content');
        $(() => {
            $('.table').DataTable({
                serverSide: true,
                processing: true,
                ordering: true,
                paging: true,
                searching:true,
                autoWidth:true,
                ajax: {
                    type: 'POST',
                    url: `{{route('alternative.data')}}`,
                    data: {_token: _token}
                },
                columns: [
                    {
                        name: 'alt_name',
                        data: 'alt_name',
                        className: 'align-middle',
                        render: (value, a, data) => {
                            let edit = `{{route('alternative.edit', ['alternative' => ':id'])}}`.replace(':id', data.id);
                            return `<a href="${edit}">${value}</a>`;
                        }
                    },
                    {
                        className: 'align-middle',
                        name: 'alt_phone',
                        data: 'alt_phone'
                    },
                    {
                        className: 'align-middle',
                        name: 'alt_email',
                        data: 'alt_email'
                    },
                    {
                        className: 'align-middle',
                        name: 'alt_address',
                        data: 'alt_address'
                    },
                    {
                        className: 'align-middle',
                        name: 'id',
                        data: 'id',
                        render: (value, a, data) => {
                            let urlEdit = `{{route('alternative.edit', ['alternative' => ':id'])}}`.replace(':id',`${value}`);
                            let urlDestroy = `{{route('alternative.destroy', ['alternative' => ':id'])}}`.replace(':id', `${value}`);
                            return `
                            <div class="row d-flex justify-content-center">
                                <a class="btn btn-sm btn-warning shadow-sm mr-2 mt-2 text-light" href="${urlEdit}"><i class="fas fa-edit"></i></a>
                                <form action="${urlDestroy}" method="POST" class="delete-confirm">
                                    <input type="hidden" value="${_token}" name="_token" />
                                    <input type="hidden" value="DELETE" name="_method" />
                                    <button type="submit" class="btn btn-sm btn-danger shadow-sm mr-2 mt-2 delete-confirm text-light"><i class="fas fa-trash"></i></a>
                                </form>
                            </div>

                            `;
                        }
                    },
                ],
                drawCallback: () => {
                    $(".datatable-add-button").remove();
                    $('#DataTables_Table_0_filter').prepend(`
                        <a  class='btn btn-info btn-sm mr-2 datatable-add-button' href="{{route('alternative.create')}}"><i class='fa fa-plus'></i> Tambah</a>
                    `);
                    setFormDeleteConfirmListener();
                }
            });
        })
    </script>
@endsection

resources/views/count_result.blade.php
@extends('layouts.app')

@section('title')
    Hasil Perhitungan Metode Moora
@endsection

@section('content')
    <div class="row" id="top">
        <div class="col-12">
            <div class="card border-0 shadow w-100">
                <div class="card-body">
                    <h2 class="card-title font-weight-bold mb-3">Tabel Kriteria</h2>
                    <table class="table table-hover">
                        <thead class="">
                            <th>Kriteria</th>
                            <th>Jenis</th>
                            <th>Bobot</th>
                        </thead>
                        <tbody>
                            @foreach ($criteria as $item)
                            <tr>
                                <td>{{$item->crt_name}}</td>
                                <td>{{$item->crt_type == '1' ? 'Benefit' : 'Cost'}}</td>
                                <td>{{$item->crt_weight}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card border-0 shadow w-100">
                <div class="card-body">
                    <h2 class="card-title font-weight-bold mb-3">Tabel Pencocokan</h2>
                    <table class="table table-hover">
                        <thead class="">
                            <tr>
                                <th>Alt.</th>
                               @foreach ($criteria as $item)
                                   <th class="header-th text-center" data-name="{{strtolower(str_replace(" ", "_", $item->crt_name))}}">{{$item->crt_name}}</th>
                               @endforeach
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($alternatives as $item)
                                <tr>
                                    <td>{{$item->alt_name}}</td>
                                    @foreach ($item->normalization->detail as $val)
                                        <td class="text-center">{{$val->label}}</td>
                                    @endforeach
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card border-0 shadow w-100">
                <div class="card-body">
                    <h2 class="card-title font-weight-bold mb-3">Konversi Tabel Pencocokan</h2>
                    <table class="table table-hover">
                        <thead class="">
                            <tr>
                                <th>Alt.</th>
                               @foreach ($criteria as $item)
                                   <th class="header-th text-center" data-name="{{strtolower(str_replace(" ", "_", $item->crt_name))}}">{{$item->crt_name}}</th>
                               @endforeach
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($alternatives as $item)
                                <tr>
                                    <td>{{$item->alt_name}}</td>
                                    @foreach ($item->normalization->detail as $val)
                                        <td class="text-center">{{$val->nrmlzn_value}}</td>
                                    @endforeach
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card border-0 shadow w-100">
                <div class="card-body">
                    <h2 class="card-title font-weight-bold mb-3">Tabel Normalisasi Matrix</h2>
                    <table class="table table-hover">
                        <thead class="">
                            <tr>
                                <th>Alt.</th>
                               @foreach ($criteria as $item)
                                   <th class="header-th text-center" data-name="{{strtolower(str_replace(" ", "_", $item->crt_name))}}">{{$item->crt_name}}</th>
                               @endforeach
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($normalizedMatrix as $item => $mtx)
                                <tr>
                                    <td>{{$item}}</td>
                                    @foreach ($mtx as $val)
                                        <td class="text-center">{{number_format($val, 4, ',', '.')}}</td>
                                    @endforeach
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card border-0 shadow w-100">
                <div class="card-body">
                    <h2 class="card-title font-weight-bold mb-3">Tabel Hasil Menghitung Nilai Optimasi</h2>
                    <table class="table table-hover">
                        <thead class="">
                            <tr>
                                <th>Altternative</th>
                                <th>Nilai Optimasi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $item)
                                <tr>
                                    <td>{{$item['alt_name']}}</td>
                                    <td>{{number_format($item['value'], 4, ',', '.')}}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-12">
            <form action="{{route('result_save')}}" method="post">
                @csrf
                <div class="card border-0 shadow w-100">
                    <div class="card-body">
                        <h2 class="card-title font-weight-bold mb-3">Tabel Hasil Perankingan</h2>
                        <table class="table table-hover" id="ranking">
                            <thead class="">
                                <tr>
                                    <th>Ranking</th>
                                    <th>Altternative</th>
                                    <th>Nilai</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $i = 1;
                                    $data = collect($data)->sortByDesc('value');

                                @endphp
                                @foreach ($data as $key => $item)
                                <tr>
                                        <td>#{{$i++}}</td>
                                        <td>{{$item['alt_name']}}</td>
                                        <td>{{number_format($item['value'], 4, ',', '.')}}</td>
                                        <td><input type="hidden" name="results[{{$key}}][rslt_dt_value]" value="{{$item['value']}}"></td>
                                        <td><input type="hidden" name="results[{{$key}}][rslt_dt_alt]" value="{{$item['alt_name']}}"></td>
                                        <td><input type="hidden" name="results[{{$key}}][rslt_dt_rank]" value="{{$loop->iteration}}"></td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="row col-12 mt-3 ">
                            <button class=" mx-2 btn btn-secondary">Kembali</button>
                            <button class=" mx-2 btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    <script>
        $(() => {
            $('#ranking').DataTable({
                searching: false,
                "ordering": false,
                info: false,
                show: false,
                "order": [[ 2, "desc" ]]
            });
        })
    </script>
@endsection

resources/views/crieria.blade.php
@extends('layouts.app')

@section('title')
    Criteria
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card border-0 shadow w-100">
                <div class="card-body">
                    <table class="table table-hover">
                        <thead class="">
                            <tr>
                                <th>Kriteria</th>
                                <th>Bobot</th>
                                <th>Jenis</th>
                                <th width="45%">Keterangan</th>
                                <th class="d-none" width="15%"></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        let datatable = null;
        let _token = $('meta[name=csrf-token]').attr('content');
        $(() => {
            $('.table').DataTable({
                serverSide: true,
                processing: true,
                ordering: true,
                paging: true,
                searching:true,
                autoWidth:true,
                ajax: {
                    type: 'POST',
                    url: `{{route('criteria.data')}}`,
                    data: {_token: _token}
                },
                columns: [
                    {
                        name: 'criterias.crt_name',
                        data: 'crt_name',
                        className: 'align-middle',
                    },
                    {
                        className: 'align-middle',
                        data: 'crt_weight',
                        name: 'criterias.crt_weight'
                    },
                    {
                        className: 'align-middle',
                        data: 'type',
                        name: 'criterias.crt_type',
                    },
                    {
                        className: 'align-middle',
                        data: 'crt_desc',
                        name: 'criterias.crt_desc'
                    },
                    {
                        className: 'align-middle d-none',
                        name: 'id',
                        data: 'id',
                        render: (value, a, data) => {
                            let urlEdit = `{{route('criteria.edit', ['criterion' => ':id'])}}`.replace(':id',`${value}`);
                            let urlDestroy = `{{route('criteria.destroy', ['criterion' => ':id'])}}`.replace(':id', `${value}`);
                            return `
                            <div class="row d-flex justify-content-center">
                                <a class="btn btn-sm btn-warning shadow-sm mr-2 mt-2 text-light" href="${urlEdit}"><i class="fas fa-edit"></i></a>
                                <form action="${urlDestroy}" method="POST" class="delete-confirm">
                                    <input type="hidden" value="${_token}" name="_token" />
                                    <input type="hidden" value="DELETE" name="_method" />
                                    <button type="submit" class="btn btn-sm btn-danger shadow-sm mr-2 mt-2 delete-confirm text-light"><i class="fas fa-trash"></i></a>
                                </form>
                            </div>

                            `;
                        }

                    },
                ],
                order: [[4, 'asc']]
                // drawCallback: () => {
                //     $(".datatable-add-button").remove();
                //     $('#DataTables_Table_0_filter').prepend(`
                //         <a  class='btn btn-info btn-sm mr-2 datatable-add-button' href="{{route('criteria.create')}}"><i class='fa fa-plus'></i> Tambah</a>
                //     `);
                //     setFormDeleteConfirmListener();
                // }
            });
        })
    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('title')

@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card border-0 shadow"m style="min-height: 70vh">
                <div class="card-body ">

                    <div id="container" class="w-100">

                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="d-none" id="cat" data-value='{{$cat}}'></div>
    <div class="d-none" id="value" data-value='{{$value}}'></div>
    <script>
        $(() => {
            let cat = JSON.parse($('#cat').attr('data-value'));
            let value = JSON.parse($('#value').attr('data-value'));
            var chart = Highcharts.chart('container', {

                title: {
                    text: 'Hasil Perhitungan Terakhir'
                },

                subtitle: {
                    text: 'Made Decision Support System'
                },

                xAxis: {
                    categories: cat
                },

                series: [{
                    type: 'column',
                    colorByPoint: true,
                    data: value,
                    showInLegend: false,
                    name: 'nilai'
                }]

            });

        })
    </script>
@endsection

resources/views/selection.blade.php
@extends('layouts.app')

@section('title')
    Pemilihan
@endsection

@section('content')
    <div class="row" id="top">
        <div class="col-12">
            <div class="card border-0 shadow w-100">
                <div class="card-body">
                    <h2 class="card-title font-weight-bold mb-3">Tabel Pencocokan</h2>
                    <table class="table table-hover">
                        <thead class="">
                            <tr>
                                <th>Alt.</th>
                               @foreach ($criteria as $item)
                                   <th class="header-th text-center" data-name="{{strtolower(str_replace(" ", "_", $item->crt_name))}}">{{$item->crt_name}}</th>
                               @endforeach
                               <th>#</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($alternatives as $item)
                                <tr>
                                    <td>{{$item->alt_name}}</td>
                                    @foreach ($item->normalization->detail as $val)
                                        <td class="text-center">{{$val->label}}</td>
                                    @endforeach
                                    <td class="tesxt-center row">
                                        <button data-name="{{$item->alt_name}}" data-id="{{$item->normalization->id}}" class="mx-1 btn btn-default btn-sm edit-normalization"><i class="fas fa-edit"></i> </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer text-right">
                    <form method="POST" action="{{route('count')}}" @if($zero_value > 0) onclick="(e) => e.preventDefault(); notify('Masih ada nilai nol', 'warning', 'WARNING'); return false;"  @endif>
                        @csrf
                        @method('PUT')
                        <button type="submit"  class="btn bg-pink">HITUNG</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-normalization" tabindex="-1" role="dialog" aria-labelledby="modal-normalizationTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-body">

                </div>
            </div>
        </div>
    </div>
    <script>
        $(() => {
            $('button.edit-normalization').click(e => {
                let id = $(e.currentTarget).attr('data-id');
                let url = `{{route('selection.edit', ':id')}}`.replace(':id', id);
                $.ajax({
                    type: "GET",
                    url: url,
                    data: {},
                    dataType: "json",
                    success: function (response) {
                        $("#modal-body").html(response.data);
                        $('#modal-title').html($(e.currentTarget).attr('data-name'));
                        $('#modal-normalization').modal('show');
                    },
                    error: (xhr, error, status) => {
                        notify(xhr.responseJSON.message, 'error', error);
                    }
                });
            });
        });
    </script>
@endsection