routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'web']], function () {
    Route::post('/alternative/data', 'AlternativeController@data')->name('alternative.data');
    Route::resource('/alternative', 'AlternativeController');

    Route::post('/criteria/data', 'CriteriaController@data')->name('criteria.data');
    Route::resource('/criteria', 'CriteriaController');

    Route::post('/selection/data', 'SelectionController@data')->name('selection.data');
    Route::resource('/selection', 'SelectionController');

    Route::put('/count-result', 'SelectionController@count')->name('count');
    Route::post('/save-result', 'SelectionController@save_results')->name('result_save');
});

resources/views/forms/alternative_form.blade.php
@extends('layouts.app')

@section('title')
    @if (!isset($data->id))
        Tambah Data Alternatif
    @else
        Rubah Data Alternatif
    @endif
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card border-0 shadow w-100">
                <div class="card-body">
                    <form id="alt-form" action="@if(isset($data->id)) {{route('alternative.update', ['alternative' => $data->id])}} @else {{route('alternative.store')}} @endif" method="POST">
                        @csrf
                        @if (isset($data->id))
                            @method('PUT')
                        @endif
                        <div class="form-group">
                            <label for="">Nama</label>
                            <input type="text" name="alt_name" id="alt_name" value="{{old('alt_name') ? old('alt_name') : ((isset($data->id)) ? $data->alt_name : null )}}" class="form-control @error('alt_name') is-invalid @enderror" placeholder="Masukan nama alternatif" required maxlength="100">
                            @error('alt_name')
                                {{$message}}
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">No. Telepon</label>
                            <input type="text" name="alt_phone" id="alt_phone" value="{{old('alt_phone') ? old('alt_phone') : ((isset($data->id)) ? $data->alt_phone : null )}}" class="form-control @error('alt_phone') is-invalid @enderror" placeholder="Masukan nomor telepon alternatif" required maxlength="100">
                            @error('alt_phone')
                                {{$message}}
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Email</label>
                            <input type="email" name="alt_email" id="alt_email" value="{{old('alt_email') ? old('alt_email') : ((isset($data->id)) ? $data->alt_email : null )}}" class="form-control @error('alt_email') is-invalid @enderror" placeholder="Masukan email alternatif" required maxlength="100">
                            @error('alt_email')
                                {{$message}}
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Alamat</label>
                            <textarea required name="alt_address" id="alt_address" class="form-control @error('alt_address') is-invalid @enderror" placeholder="Masukan alamat alternatif" cols="30" rows="5">{{old('alt_address') ? old('alt_address') : ((isset($data->id)) ? $data->alt_address : null )}}</textarea>
                            @error('alt_address')
                                {{$message}}
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-block bg-pink">SIMPAN</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(() => {
            $('#alt-form').validate()
        })
    </script>
@endsection

resources/views/forms/criteria_form.blade.php
@extends('layouts.app')

@section('title')
    @if (!isset($data->id))
        Tambah Data Kriteria
    @else
        Update Data Kriteria
    @endif
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card border-0 shadow w-100">
                <form action="{{isset($data->id) ? route('criteria.update', $data->id) : route('criteria.store')}}" method="POST" id="form-criteria">
                    @csrf
                    @if (isset($data->id))
                        @method('PUT')
                    @endif
                    <div class="card-body">
                        <div class="form-group">
                            <label for="crt_name">Nama Kriteria</label>
                            <input type="text" value="{{old('crt_name') ? old('crt_name') : (isset($data->id) ? $data->crt_name : '')}}" placeholder="Masukan nama kriteria" name="crt_name" id="crt_name" class="form-control @error('crt_name') is-invalid @enderror" required>
                            @error('crt_name')
                                <div class="invalid-feedback">
                                    {{$message}}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="crt_weight">Bobot Kriteria</label>
                            <input type="number" value="{{old('crt_weight') ? old('crt_weight') : (isset($data->id) ? $data->crt_weight : '')}}" name="crt_weight" id="crt_weight" class="form-control @error('crt_weight') is-invalid @enderror" placeholder="Masukan bobot kriteria" required>
                            @error('crt_weight')
                                {{$message}}
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Jenis Kriteria</label>
                            <select name="crt_type" id="crt_type" class="form-control">
                                <option @if(old('crt_type') == '1' || (isset($data->id) and $data->crt_type == '1')) selected @endif value="1">Benefit</option>
                                <option @if(old('crt_type') == '0' || (isset($data->id) and $data->crt_type == '0')) selected @endif value="0">Cost</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="crt_desc">Deskripsi Kriteria <small class="text-muted">(optional)</small></label>
                            <textarea name="crt_desc" id="crt_desc" placeholder="Deskripsi kriteria" cols="30" rows="5" class="form-control @error('crt_desc') is-invalid @enderror">{{old('crt_desc') ? old('crt_desc') : (isset($data->id) ? $data->crt_desc : '')}}</textarea>
                            @error('crt_desc')
                                {{$message}}
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-block bg-pink">SIMPAN</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(() => {
            $('#form-criteria').validate({});
        })
    </script>
@endsection

resources/views/forms/form_normalization.blade.php
<form action="{{route('selection.update', ['selection' => $selection->id])}}" method="POST" id="form-normalization">
    @csrf
    @method('PUT')
    @foreach ($criteria as $key => $item)

        <div class="form-row mb-3">
            <div class="form-group col-12 mb-0">
                <label>{{$item->crt_name}}</label>
            </div>
            {{-- <div class="input-group col-6">
                <div class="input-group-prepend">
                    <span class="input-group-text">Label</span>
                </div>
                <input type="text" value="{{$normalization[$key]['nrmlzn_label']}}" name="nrmlzn[{{$key}}][nrmlzn_label]" id="nrmlzn_label{{$item->id}}" class="form-control" required>
            </div> --}}
            <div class="input-group col-12">
                <div class="input-group-prepend">
                    <span class="input-group-text">{{$criteriaConfig[$item->crt_name][0]['unit'] ?? 'Nilai'}}</span>
                </div>
                <input min="{{$criteriaConfig[$item->crt_name][0]['min'] ?? 10}}" step=".01" type="number"value="{{$normalization[$key]['nrmlzn_label']}}"  name="nrmlzn[{{$key}}][nrmlzn_value]" id="nrmlzn_value{{$item->id}}" class="form-control" required>
            </div>
            <input type="hidden" name="nrmlzn[{{$key}}][criteria_id]" value="{{$item->id}}">
            <input type="hidden" name="nrmlzn[{{$key}}][normalization_id]" value="{{$selection->id}}">
            <input type="hidden" name="nrmlzn[{{$key}}][crt_name]" value="{{$item->crt_name}}">
        </div>
    @endforeach
    <div class="form-group mt-3">
        <button type="submit" class="btn btn-block bg-pink">SIMPAN</button>
    </div>
</form>